pagopa/rtp-sender

- src/main/docker/Dockerfile
> fix: Fix typo.

- src/main/terraform/container_app.tf
> Fix deploy

- src/main/java/it/gov/pagopa/rtp/sender/service/activation/ActivationPayerServiceImpl.java
> feat: Mod formatting to push a new release.

- src/main/java/it/gov/pagopa/rtp/sender/repository/activation/ActivationDB.java
- src/main/java/it/gov/pagopa/rtp/sender/repository/activation/ActivationEntity.java
- src/main/java/it/gov/pagopa/rtp/sender/service/oauth/Oauth2TokenService.java
> fix: Fix to push first release.

- .github/workflows/post-merge.yml
> fix: Second test to trigger release.

- src/test/postman/RTP-component-test.postman_collection.json
- src/test/postman/uat.postman_environment.json
This PR fixes the failing Callback Send test in the RTP component Postman collection. The request body was not aligned with the expected structure, leading to a 400 Bad Request. The test now correctly builds the payload and uses a properly formatted OrgnlMsgId extracted from the Location header.
- Fixed the request body for Callback Send.
- Added a second Send RTP (Send RTP for Callback Send) request to generate a valid resourceId and ensure the SRTP is in a valid state before sending the callback. 
- Added a test script to extract and format OrgnlMsgId (UUID without hyphens).
- Updated the Postman collection with working local tests.
Ensures callback logic is correctly tested post-deploy in UAT and avoids false negatives in automated test runs.
Manual validation via Postman in local …
> fix: [SRTP-546] align Callback Send in postman test

- src/main/java/it/gov/pagopa/rtp/sender/controller/rtp/SendAPIControllerImpl.java
- src/main/java/it/gov/pagopa/rtp/sender/service/rtp/SendRTPServiceImpl.java
- src/main/java/it/gov/pagopa/rtp/sender/service/rtp/handler/SendRtpHandler.java
- src/main/java/it/gov/pagopa/rtp/sender/service/rtp/handler/SendRtpProcessorImpl.java
moved logs from SendAPIController to SendRtpProcessorImpl
In failure MDC was not being populated and no SP was being log
> fix: [SRTP-563] mdc logs not showing on errors in send rtp

- src/main/java/it/gov/pagopa/rtp/sender/service/rtp/SendRTPServiceImpl.java
Removed payerId log
payerId infos should not be displayed
> chore: [SRTP-563] remove unnecessary log for payerId

- src/main/terraform/container_app.tf
- src/main/terraform/data.tf
- src/main/terraform/env/cstar-d-weu-rtp/terraform.tfvars
- src/main/terraform/env/cstar-p-weu-rtp/terraform.tfvars
- src/main/terraform/env/cstar-u-weu-rtp/terraform.tfvars
- src/main/terraform/locals.tf
- src/main/terraform/variables.tf
Move azurerm_container_app_environment_storage to cstar-infrastructure, under the folder rtp-common
> fix: [SRTP-596] Move azurerm_container_app_environment_storage to cstar

- src/main/java/it/gov/pagopa/rtp/sender/service/callback/CallbackHandler.java
- src/test/java/it/gov/pagopa/rtp/sender/service/callback/CallbackHandlerTest.java
Currently, when we receive a callback related to a send operation, the TransactionStatus.ACTC value is not being handled as a valid case in the CallbackHandler. As a result, the RTP flow doesn't recognize it and incorrectly falls back to setting the RtpStatus to ERROR_SEND.
This pull request introduces a simple but important change: it adds support for the ACTC status in the logic of the triggerStatus(...) method. Specifically, it includes ACTC in the same handling path as ACCP and ACWC, mapping all three statuses to the ACCEPT transition for RTPs.
- Added TransactionStatus.ACTC to the switch block in CallbackHandler.triggerStatus(...)
The TransactionStatus.ACTC value was previously not handled in the CallbackHandler, causing RTPs to incorrectly transition to ERROR_SEND even when the …
> fix: [SRTP-617] add ACTC status in the CallbackHandler

- src/main/java/it/gov/pagopa/rtp/sender/controller/rtp/SendAPIControllerImpl.java
- src/main/java/it/gov/pagopa/rtp/sender/service/callback/CallbackFieldsExtractor.java
- src/main/java/it/gov/pagopa/rtp/sender/service/rtp/SendRTPServiceImpl.java
- src/main/java/it/gov/pagopa/rtp/sender/service/rtp/handler/SendRtpProcessorImpl.java
- src/test/java/it/gov/pagopa/rtp/sender/service/rtp/handler/SendRtpProcessorImplTest.java
> fix: [SRTP-567] Remove sensitive data from logs

- src/main/java/it/gov/pagopa/rtp/sender/utils/CertificateChecker.java
- src/test/java/it/gov/pagopa/rtp/sender/utils/CertificateCheckerTest.java
Mod the certificate checker to ingore case on string.
> fix: [SRTP-676] Ignore case.

- src/main/java/it/gov/pagopa/rtp/sender/controller/callback/RequestToPayUpdateController.java
- src/main/java/it/gov/pagopa/rtp/sender/service/callback/CallbackHandler.java
- src/test/java/it/gov/pagopa/rtp/sender/controller/callback/RequestToPayUpdateControllerTest.java
- src/test/java/it/gov/pagopa/rtp/sender/service/callback/CallbackHandlerTest.java
This PR fixes a bug where the application was returning an HTTP 200 OK response even when an error occurred during the handling of a send callback(for example, due to a malformed JSON payload).
Although the error was correctly caught and logged internally, it was not properly translated into an appropriate HTTP status code in the response, which should have been 400 Bad Request as per the specification.
- In `CallbackHandler.java` it has been changed so that when the `TransactionStatus` is ERROR or unrecognized (the default), an `IllegalStateException` is now thrown with a clear message.
- In `RequestToPayUpdateController.java`, added explicit handling of `IllegalStateException`, returning a 400 Bad Request.
To ensure that whenever logical errors or invalid states occur during callback …
> fix: [SRTP-623] return 400 Bad Request instead of 200 OK on callback error

- src/main/terraform/env/itn-dev/terraform.tfvars
> fix: variables@itn-dev 

- .github/workflows/build-n-push-main.yml
> chore: Fix action itn depoly.

- openapi/send.openapi.yaml
- src/main/java/it/gov/pagopa/rtp/sender/controller/rtp/SendAPIControllerImpl.java
This PR adds the _OpenAPI_ specifications the new   `findRtpByNoticeNumber ` _RESTful API_: the defined _API_ accepts the `noticeNumber` query param as input and returns the associated _RTP_.
- updated `send.openapi.yaml` with the new _API_ specs;
- added a stub of implementation in `SendAPIControllerImpl`.
This is preparatory to later implement said _API_, which is needed for testing and tech support.
> feat: [SRTP-715] add find RTP by Notice Number API in send OpenAPI

- src/main/java/it/gov/pagopa/rtp/sender/service/callback/CallbackHandler.java
- src/test/java/it/gov/pagopa/rtp/sender/service/callback/CallbackHandlerTest.java
This PR introduces a change in the `triggerStatus` method of the `CallbackHandler` class to explicitly treat the `ACWC` transaction status as unsupported. This behavior aligns with the expected flow where a reserved acceptance (`ACWC`) is considered invalid and must be handled as an error case.
Any unsupported status, including `ACWC`, now logs a warning and results in an `IllegalStateException`, clearly indicating that the input status is not part of the allowed transaction flow.
- Replaced handling of unsupported `TransactionStatus` values (including `ACWC`) with an inline error-throwing mechanism.
- Removed previous call to `triggerErrorSendRtp(...)`, no longer relevant for unsupported statuses.
The state `ACWC` (reserved acceptance) is not considered a valid or permitted transition in …
> fix: [SRTP-697] Handle ACWC status as unsupported callback

- .github/workflows/scan-cve.yml
- .github/workflows/send-notification.yml
This is a replica of PR https://github.com/pagopa/rtp-activator/pull/154
> fix: [SRTP-735] Script send notification

- src/main/terraform/env/itn-dev/terraform.tfvars
- src/main/terraform/env/itn-prod/terraform.tfvars
- src/main/terraform/env/itn-uat/terraform.tfvars
This PR adds the required secrets and configuration to allow the sender service to authenticate with the MIL Auth system.
See also https://github.com/pagopa/cstar-securehub-infra/pull/160
Added the following secrets to rtp_environment_secrets in itn-dev and itn-prod:
- MIL_AUTH_CLIENT_ID
- MIL_AUTH_CLIENT_SECRET
Added the _MIL_AUTH_TOKEN_URL_ property to rtp_environment_configs with the URL of the MIL token endpoint.
Changes applied in dev e uat
The sender service needs to authenticate with MIL Auth to obtain a token before calling the Authenticator. These secrets and configuration entries enable that flow to happen securely and in a configurable, environment-specific manner.
By externalizing credentials and the token URL, we maintain flexibility and security while aligning with …
> chore: [SRTP-756] Add mil auth client secrets

- src/main/java/it/gov/pagopa/rtp/sender/RtpSenderApplication.java
- src/main/java/it/gov/pagopa/rtp/sender/configuration/Oauth2ClientConfig.java
- src/main/java/it/gov/pagopa/rtp/sender/configuration/Oauth2ConfigProperties.java
- src/main/java/it/gov/pagopa/rtp/sender/configuration/mtlswebclient/DefaultWebClientFactory.java
- src/main/resources/application.yaml
- src/test/java/it/gov/pagopa/rtp/sender/configuration/mtlswebclient/DefaultWebClientFactoryTest.java
- src/test/resources/application.yaml
This PR aims to create an _OAuth2_ client that manages authentication with [mil-auth](https://github.com/pagopa/mil-auth) _Identity Provider_: this client is then injected into the default `WebClient` in order to perform authenticated calls like `findActivationByPayerId`.
- Added _Spring Security OAuth2_ configs in `application.yaml`;
- created `Oauth2ConfigProperties` that reference above configs;
- created `Oauth2ClientConfig ` responsible for exposing relevant _OAuth2_ beans;
- injected above beans in `DefaultWebClientFactory` to be used with `simpleWebClient`.
This is needed to perform authenticated call to internal services.
> feat: [SRTP-751] create oauth2 token client for internal calls

- src/main/resources/application.yaml
> fix: [SRTP-766] fix typo.

- .github/workflows/post-merge.yml
Adds a step to the post-merge action to deploy the service in the production environment.
> feat: [SRTP-795] Add action to deploy sender in prod env after merge.

- .github/workflows/post-merge.yml
- src/test/java/it/gov/pagopa/rtp/sender/configuration/ActivationPropertiesConfigTest.java
> fix: [SRTP-807] fix prod step for deploy.
